package tests.mock;

import haxe.Exception;

/**
    Error used by the RandomGeneratorMock when it has run out of provided mock results
**/
class NoMockResult extends Exception {}